language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --dev

script:
  - vendor/bin/phpcs --standard=PSR2 litle
  - vendor/bin/phpunit

notifications:
  email:
    - sumi.yadav@gmail.com
